name: e-commerce
services:
  db:
    container_name: postgres
    image: postgres:14.23-alpine3.23
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=e-commerce
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.7-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  db_data:
  rabbitmq_data:
