FROM eclipse-temurin:26-jdk AS build
WORKDIR /app

ENV RABBIT_USER=$RABBIT_USER
ENV RABBIT_PASS=$RABBIT_PASS
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS

# COPY pom.xml .
# RUN mvn dependency:go-offline

# COPY src ./src
COPY . .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:26-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]