spring:
  application:
    name: e-commerce
  jpa:
    hibernate:
      ddl-auto: update
  config:
      import: optional:file:.env[.properties]
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
  datasource:
    url: jdbc:postgresql://db:5432/e-commerce
    username: ${DB_USER}
    password: ${DB_PASS}
