spring:
  application:
    name: e-commerce
  jpa:
    hibernate:
      ddl-auto: update
  config:
      import: optional:file:.env[.properties]
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: ${DB_USER}
    password: ${DB_PASS}
  # variaveis para o email 
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_AUTH}
          starttls:
            enable: ${EMAIL_STARTTLS}
  
